AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyRDSSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the secret for my RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@\/'

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: MyRDSSecrets
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSSecrets}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${MyRDSSecrets}:SecretString:password}}'
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: 'rds-instance'
